### ISSUE TITLE
Implement support for tab-completion in PowerShell

### ISSUE THREAD

**Issue by deaddog** [deaddog/GitHubConsole#33]

**Comment by MikaelElkiaer** [comment]
:+1:

**Comment by deaddog** [comment]
Besides completion for the command names, is there any other type of tab-completion that might be nice? @mikaelec

**Comment by MikaelElkiaer** [comment]
Perhaps: assignees, labels.

**Comment by deaddog** [comment]
Perhaps... Currently that will require an http request, making tab completion rather slow. Or alternatively caching labels / assignees somewhere. Will look into it.
