### ISSUE TITLE
--close argument for the issues command to simply close an issue

### ISSUE THREAD

**Issue by MikaelElkiaer** [deaddog/GitHubConsole#37]
This could be useful for closing no longer relevant issues, or simply issues forgotten to close on commit.

**Comment by deaddog** [comment]
The argument/parameter is implemented in such a way that it can be used with other parameters. So closing a duplicate can be done like this:
`github issues 2 --close --set-labels duplicate`
or by loading the labels-menu:
`github issues 2 --close --edit-labels`
