### ISSUE TITLE
Option for verbose/non-verbose

### ISSUE THREAD

**Issue by MikaelElkiaer** [deaddog/GitHubConsole#9]
E.g. when listing issues, simple list with ids and titles for easy reference when closing issues would be nice. 
A more verbose mode for viewing assignees and labels should be optional.

**Comment by deaddog** [comment]
@mikaelec: The system supports a flexible output format for issue-listing (which can be specified as argument or in config) and aliasing. That way you can define a default format (non-verbose) and an alias command for verbose listing.
Could that be a fix for this issue? Or are there other specific requirements?

**Comment by deaddog** [comment]
@mikaelec bump

**Comment by MikaelElkiaer** [comment]
@deaddog :+1:
